version: '3'
services:
  mysql:
    restart: always
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ${MYSQL_DIR}:/mydir
      - ${MYSQL_DIR}/data:/var/lib/mysql
      - ${MYSQL_DIR}/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ${MYSQL_DIR}/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_ROOT_HOST}"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
