spring:
   datasource:
        write:
           url: jdbc:mysql://localhost:3306/test
           username: root
           password: root
           driver-class-name: com.mysql.cj.jdbc.Driver
        read:
            url: jdbc:mysql://localhost:3306/test
            username: root
            password: root
            driver-class-name: com.mysql.cj.jdbc.Driver
