server:
    port: 8080

logging:
     level:
          tk.mybatis: DEBUG
          
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/stock?characterEncoding=utf8&useSSL=true
        username: root
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        templateEncoding: UTF-8
        contentType: text/html

    mail:
        host: smtp.qq.com
        username: 773000735@qq.com
        password: bygeapnfwejybebg #开启POP3之后设置的客户端授权码
        default-encoding: UTF-8
        port: 465
        properties:
            mail:
                smtp:
                    ssl:
                        enable: true


swagger-ui: true



